AppDigestoVillaNueva/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from .views import *

urlpatterns = [
    path('', RedirectView.as_view(url='/home')),
    path('home/', login_required(index), name='index'),
    path('decreto-crear/', login_required(DecretoCreateView.as_view()), name='decreto_create'),
    path('decreto-editar/<int:pk>/', login_required(DecretoUpdateView.as_view()), name='decreto_update'),
    path('decreto-listar/', login_required(DecretoListView.as_view()), name='decreto_list'),
    path('decreto-publicar/<int:pk>/', login_required(DecretoPublicarView.as_view()), name='decreto_public'),
    path('decreto-publicar-masivo', login_required(DecretoPublicarMasivoView.as_view()), name='decreto_public_masivo'),
    path('decreto-eliminar/<int:pk>/', login_required(DecretoDeleteView.as_view()), name='decreto_delete'),
    path('decreto-pdf/<int:pk>/', login_required(decreto_pdf_view), name='decreto_pdf'),
    path('ordenanza-crear/', login_required(OrdenanzaCreateView.as_view()), name='ordenanza_create'),
    path('ordenanza-editar/<int:pk>/', login_required(OrdenanzaUpdateView.as_view()), name='ordenanza_update'),
    path('ordenanza-listar/', login_required(OrdenanzaListView.as_view()), name='ordenanza_list'),
    path('ordenanza-publicar/<int:pk>/', login_required(OrdenanzaPublicarView.as_view()), name='ordenanza_public'),
    path('ordenanza-publicar-masivo', login_required(OrdenanzaPublicarMasivoView.as_view()), name='ordenanza_public_masivo'),
    path('ordenanza-eliminar/<int:pk>/', login_required(OrdenanzaDeleteView.as_view()), name='ordenanza_delete'),
    path('ordenanza-pdf/<int:pk>/', login_required(ordenanza_pdf_view), name='ordenanza_pdf'),
    path('resolucion-crear/', login_required(ResolucionCreateView.as_view()), name='resolucion_create'),
    path('resolucion-editar/<int:pk>/', login_required(ResolucionUpdateView.as_view()), name='resolucion_update'),
    path('resolucion-listar/', login_required(ResolucionListView.as_view()), name='resolucion_list'),
    path('resolucion-publicar/<int:pk>/', login_required(ResolucionPublicarView.as_view()), name='resolucion_public'),
    path('resolucion-publicar-masivo', login_required(ResolucionPublicarMasivoView.as_view()), name='resolucion_public_masivo'),
    path('resolucion-eliminar/<int:pk>/', login_required(ResolucionDeleteView.as_view()), name='resolucion_delete'),
    path('resolucion-pdf/<int:pk>/', login_required(resolucion_pdf_view), name='resolucion_pdf'),
    path('declaracion-crear/', login_required(DeclaracionCreateView.as_view()), name='declaracion_create'),
    path('declaracion-editar/<int:pk>/', login_required(DeclaracionUpdateView.as_view()), name='declaracion_update'),
    path('declaracion-listar/', login_required(DeclaracionListView.as_view()), name='declaracion_list'),
    path('declaracion-publicar/<int:pk>/', login_required(DeclaracionPublicarView.as_view()), name='declaracion_public'),
    path('declaracion-publicar-masivo', login_required(DeclaracionPublicarMasivoView.as_view()), name='declaracion_public_masivo'),
    path('declaracion-eliminar/<int:pk>/', login_required(DeclaracionDeleteView.as_view()), name='declaracion_delete'),
    path('declaracion-pdf/<int:pk>/', login_required(declaracion_pdf_view), name='declaracion_pdf'),
    path('boletinoficial-crear', crear_boletin, name='boletinoficial_create'),
    path('boletinoficial/<int:pk>/', login_required(boletin_detail), name='boletinoficial_detail'),
    path('boletinoficial-listar/', login_required(BoletinOficialListView.as_view()), name='boletinoficial_list'),
    path('boletinoficial-pdf/<int:pk>/', login_required(boletin_pdf_view), name='boletinoficial_pdf'),
    path('boletinoficial-publicar/<int:pk>/', login_required(BoletinOficialPublicarView.as_view()), name='boletinoficial_public'),
    path('boletinoficial-eliminar/<int:pk>/', login_required(BoletinOficialDeleteView.as_view()), name='boletinoficial_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DigestoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppDigestoVillaNueva.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

AppDigestoVillaNueva/models.py
from django.db import models
from datetime import date
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from django.utils import timezone
import os


# Create your models here.

class Documento(models.Model):
    fecha_creacion = models.DateField(default=timezone.now)
    descripcion = models.TextField(max_length=2000)
    publicado = models.BooleanField(default=False)
    eliminado = models.BooleanField(default=False)
    creado_por = models.ForeignKey(User, on_delete=models.PROTECT, related_name='documentos_creados')
    ultima_modificacion = models.DateTimeField(auto_now=True)
    modificado_por = models.ForeignKey(User, on_delete=models.PROTECT, related_name='documentos_modificados')

def upload_to_decreto(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'Decretos/Decreto-{0}-{1:04d}{2}'.format(instance.anio, instance.numero_decreto, extension)

class Decreto(Documento):
    numero_decreto = models.PositiveIntegerField(default=1)
    anio = models.IntegerField(default=date.today().year)
    fecha_publicacion = models.DateField(blank=True, null=True)
    archivo_pdf = models.FileField(upload_to=upload_to_decreto, validators=[FileExtensionValidator(['pdf'], message="ERROR, el archivo tiene que estar en formato PDF.")], blank=True, null=True)

    def __str__(self):
        return "Decreto- " + str(self.anio) + "/" + str(self.numero_decreto)
    
    def save(self, *args, **kwargs):
        # Si el objeto ya existe y se está actualizando el archivo
        if self.pk and self.archivo_pdf:
            try:
                # Intenta obtener el objeto antiguo
                old_file = Decreto.objects.get(pk=self.pk).archivo_pdf
            except Decreto.DoesNotExist:
                pass
            else:
                # Si el archivo antiguo existe y es diferente del nuevo, bórralo
                if old_file and old_file != self.archivo_pdf:
                    old_file.delete()

        # Llama al método save de la clase base para continuar con el procesamiento estándar
        super().save(*args, **kwargs)
    
def upload_to_ordenanza(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'Ordenanzas/Ordenanza-{0}-{1:04d}{2}'.format(instance.anio, instance.numero_ordenanza, extension)

class Ordenanza(Documento):
    numero_ordenanza = models.PositiveIntegerField(default=1)
    anio = models.IntegerField(default=date.today().year)
    fecha_publicacion = models.DateField(blank=True, null=True)
    archivo_pdf = models.FileField(upload_to=upload_to_ordenanza, validators=[FileExtensionValidator(['pdf'], message="ERROR, el archivo tiene que estar en formato PDF.")], blank=True, null=True)

    def __str__(self):
        return "Ordenanza- " + str(self.anio) + "/" + str(self.numero_ordenanza)
    
    def save(self, *args, **kwargs):
        # Si el objeto ya existe y se está actualizando el archivo
        if self.pk and self.archivo_pdf:
            try:
                # Intenta obtener el objeto antiguo
                old_file = Ordenanza.objects.get(pk=self.pk).archivo_pdf
            except Ordenanza.DoesNotExist:
                pass
            else:
                # Si el archivo antiguo existe y es diferente del nuevo, bórralo
                if old_file and old_file != self.archivo_pdf:
                    old_file.delete()

        # Llama al método save de la clase base para continuar con el procesamiento estándar
        super().save(*args, **kwargs)

def upload_to_resolucion(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'Resoluciones/Resolucion-{0}-{1:04d}{2}'.format(instance.anio, instance.numero_resolucion, extension)

class Resolucion(Documento):
    numero_resolucion = models.PositiveIntegerField(default=1)
    anio = models.IntegerField(default=date.today().year)
    fecha_publicacion = models.DateField(blank=True, null=True)
    archivo_pdf = models.FileField(upload_to=upload_to_resolucion, validators=[FileExtensionValidator(['pdf'], message="ERROR, el archivo tiene que estar en formato PDF.")], blank=True, null=True)

    def __str__(self):
        return "Resolucion- " + str(self.anio) + "/" + str(self.numero_resolucion)
    
    def save(self, *args, **kwargs):
        # Si el objeto ya existe y se está actualizando el archivo
        if self.pk and self.archivo_pdf:
            try:
                # Intenta obtener el objeto antiguo
                old_file = Resolucion.objects.get(pk=self.pk).archivo_pdf
            except Resolucion.DoesNotExist:
                pass
            else:
                # Si el archivo antiguo existe y es diferente del nuevo, bórralo
                if old_file and old_file != self.archivo_pdf:
                    old_file.delete()

        # Llama al método save de la clase base para continuar con el procesamiento estándar
        super().save(*args, **kwargs)

def upload_to_declaracion(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'Declaraciones/Declaracion-{0}-{1:04d}{2}'.format(instance.anio, instance.numero_declaracion, extension)

class Declaracion(Documento):
    numero_declaracion = models.PositiveIntegerField(default=1)
    anio = models.IntegerField(default=date.today().year)
    fecha_publicacion = models.DateField(blank=True, null=True)
    archivo_pdf = models.FileField(upload_to=upload_to_declaracion, validators=[FileExtensionValidator(['pdf'], message="ERROR, el archivo tiene que estar en formato PDF.")], blank=True, null=True)

    def __str__(self):
        return "Declaracion- " + str(self.anio) + "/" + str(self.numero_declaracion)
    
    def save(self, *args, **kwargs):
        # Si el objeto ya existe y se está actualizando el archivo
        if self.pk and self.archivo_pdf:
            try:
                # Intenta obtener el objeto antiguo
                old_file = Declaracion.objects.get(pk=self.pk).archivo_pdf
            except Declaracion.DoesNotExist:
                pass
            else:
                # Si el archivo antiguo existe y es diferente del nuevo, bórralo
                if old_file and old_file != self.archivo_pdf:
                    old_file.delete()

        # Llama al método save de la clase base para continuar con el procesamiento estándar
        super().save(*args, **kwargs)

def upload_to_boletin(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'BoletinOficial/BoletinOficial-{0}{1}'.format(instance.fecha_creacion, extension)

class BoletinOficial(models.Model):
    fecha_creacion = models.DateField(default=timezone.now)
    fecha_desde = models.DateField()
    fecha_hasta = models.DateField()
    publicado = models.BooleanField(default=False)
    decretos = models.BooleanField(default=False)
    resoluciones = models.BooleanField(default=False)
    ordenanzas = models.BooleanField(default=False)
    declaraciones = models.BooleanField(default=False)
    archivo_pdf = models.FileField(upload_to=upload_to_boletin, blank=True, null=True)

    def __str__(self):
        return "BoletinOficial-" + str(self.fecha_creacion)

AppDigestoVillaNueva/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, UpdateView, ListView, View
from django.urls import reverse_lazy
from datetime import date
from django.db.models import Max
from .models import Decreto
from .forms import DecretoForm
from datetime import datetime

# Create your views here.

class DecretoCreateView(CreateView):
    model = Decreto
    form_class = DecretoForm
    template_name = "decreto_create.html"
    success_url = reverse_lazy('decreto_list')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        # Obtiene el valor máximo de numero_decreto del año actual + 1
        today = date.today()
        year = today.year
        max_decreto = Decreto.objects.filter(anio=year).aggregate(Max('numero_decreto'))['numero_decreto__max']

        # Si no hay ningún decreto para el año actual, asigna 1 como valor predeterminado
        if max_decreto is None:
            max_decreto = 1
        else:
            max_decreto += 1

        # Devuelve un diccionario con el valor predeterminado para numero_decreto
        return {'numero_decreto': max_decreto}
    
    def form_valid(self, form):
        # Obtén la fecha de publicación del formulario
        fecha_publicacion = form.cleaned_data.get('fecha_publicacion')

        # Si hay una fecha de publicación, establece publicado en True
        if fecha_publicacion:
            form.instance.publicado = True

        # Llama al método form_valid de la clase base para continuar con el procesamiento estándar
        return super().form_valid(form)

class DecretoUpdateView(UpdateView):
    model = Decreto
    form_class = DecretoForm
    template_name = "decreto_edit.html"
    success_url = reverse_lazy('decreto_list')

    def form_valid(self, form):
        # Obtén la fecha de publicación del formulario
        fecha_publicacion = form.cleaned_data.get('fecha_publicacion')

        # Si hay una fecha de publicación, establece publicado en True
        if fecha_publicacion:
            form.instance.publicado = True

        # Llama al método form_valid de la clase base para continuar con el procesamiento estándar
        return super().form_valid(form)

class DecretoListView(ListView):
    model = Decreto
    template_name = "decreto_list.html"
    context_object_name = 'decretos'
    
    def get_queryset(self):
        return Decreto.objects.filter(eliminado=False).order_by('-anio', '-numero_decreto')

class DecretoDeleteView(UpdateView):
    model = Decreto
    fields = ['eliminado']

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.eliminado = True
        self.object.save()
        return redirect('decreto_list')
    
class DecretoPublicarView(UpdateView):
    model = Decreto
    fields = ['publicado']

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.publicado = True
        self.object.fecha_publicacion = date.today()
        self.object.save()
        return redirect('decreto_list')

class DecretoPublicarMasivoView(View):
    def get(self, request):
        return render(request, 'decreto_publicacion_masiva.html')

    def post(self, request):
        if 'confirmar' in request.POST:
            # Si se confirma la publicación, publicar los decretos
            decretos_a_publicar_ids = request.session.get('decretos_a_publicar_ids', [])
            decretos_a_publicar = Decreto.objects.filter(id__in=decretos_a_publicar_ids)
            for decreto in decretos_a_publicar:
                decreto.publicado = True
                decreto.fecha_publicacion = date.today()
                decreto.save()
            del request.session['decretos_a_publicar_ids']  # Limpiar la sesión
            return redirect('decreto_list')
        else:
            # Obtener las fechas y filtrar los decretos
            fecha_desde = request.POST.get('fecha_desde')
            fecha_hasta = request.POST.get('fecha_hasta')
            if fecha_desde and fecha_hasta:
                fecha_desde = datetime.strptime(fecha_desde, '%Y-%m-%d').date()
                fecha_hasta = datetime.strptime(fecha_hasta, '%Y-%m-%d').date()
                decretos = Decreto.objects.filter(fecha_creacion__range=(fecha_desde, fecha_hasta))
                decretos_a_publicar = [decreto for decreto in decretos if decreto.archivo_pdf and not decreto.fecha_publicacion]
                # Almacenar los IDs de los decretos a publicar en la sesión
                request.session['decretos_a_publicar_ids'] = [decreto.id for decreto in decretos_a_publicar]
                return render(request, 'decreto_confirmar_publicacion.html', {'decretos': decretos_a_publicar})
            else:
                return redirect('decreto_list')


def decreto_pdf_view(request, pk):
    decreto = get_object_or_404(Decreto, pk=pk)
    
    with open(decreto.archivo_pdf.path, 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        filename = 'Decreto-{0}-{1:04d}.pdf'.format(decreto.anio, decreto.numero_decreto)
        response['Content-Disposition'] = 'inline; filename="{0}"'.format(filename)
        return response

AppDigestoVillaNueva/views/views_login.py
from django.shortcuts import  redirect, render
from django.views.generic import View

# Create your views here.

def index(request):
    return render(request, 'home.html')

AppDigestoVillaNueva/templates/boletinoficial/boletin_crear.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h4 class="card-title">Generar Nuevo Boletín Oficial</h4>
    <form method="post">
      {% csrf_token %}
      <br>
      <div class="mb-3">
        <div class="row">
          <div class="col-4">
            Fecha del boletín {{ form.fecha_creacion }}
          </div>
          <div class="col-4">
            {{ form.fecha_desde.label_tag }} {{ form.fecha_desde }}
          </div>
          <div class="col-4">
            {{ form.fecha_hasta.label_tag }} {{ form.fecha_hasta }}
          </div>
        </div>
        <br>
        <h6>Seleccione los documentos a mostrar en el boletín</h6>
        <div>
          <div class="form-check form-switch">
            {{ form.decretos }} Decretos
          </div>
          <div class="form-check form-switch">
            {{ form.resoluciones }} Resoluciones
          </div>
          <div class="form-check form-switch">
            {{ form.ordenanzas }} Ordenanzas
          </div>
          <div class="form-check form-switch">
            {{ form.declaraciones }} Declaraciones
          </div>
        </div>
        <br>
        <button class="btn btn-primary float-end" type="submit">Generar boletín</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

AppDigestoVillaNueva/templates/boletinoficial/boletin_detail.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="card" style="width: 100%;">
    <div class="card-body">
        <h3>¡Boletín generado correctamente!</h3>
        <br>
        <h4 class="card-title">Boletín Oficial - {{ boletin.fecha_creacion|date:"d/m/Y" }}</h4>
        <p>Incluye los documentos publicados entre las fechas <b>{{ boletin.fecha_desde|date:"d/m/Y" }}</b> y <b>{{ boletin.fecha_hasta|date:"d/m/Y" }}</b>.</p>
        <h6>Documentos:</h6>
        <ul>
            {% for documento in documentos %}
            <li>{{ documento }}</li>
            {% endfor %}
        </ul>
        <a class="btn btn-primary float-end" href="{% url 'boletinoficial_list' %}">Ir a listado</a>
        <a class="btn btn-success float-end" href="{{ boletin.archivo_pdf.url }}" target="_blank">Descargar Boletín {{ boletin.fecha_creacion|date:"d/m/Y" }}</a>
    </div>
</div>
{% endblock %}

AppDigestoVillaNueva/templates/boletinoficial/boletin_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <h2>Boletín Oficial {% if perms.AppDigestoVillaNueva.add_boletinoficial %}<a href="{% url 'boletinoficial_create' %}" class="btn btn-primary float-end">Nuevo Boletín Oficial <i class="bi bi-file-earmark-plus"></i></a>{% endif %}</h2>
    
    <br>
    <table id="boletinoficialTable" class="table table-hover">
        <thead>
            <tr>
                <th scope="col" class="col-4">Boletín</th>
                <th scope="col" class="col-4">Fechas</th>
                <th scope="col" class="col-4">Archivo</th>
            </tr>
        </thead>
        <tbody>
            {% for boletinoficial in object_list %}
            <tr>
                <td>{{ boletinoficial.fecha_creacion|date:"d/m/Y" }}</td>
                <td><b>Desde:</b> {{ boletinoficial.fecha_desde|date:"d/m/Y" }} - <b>Hasta:</b> {{ boletinoficial.fecha_hasta|date:"d/m/Y" }}</td>
                <td>
                  <span data-bs-toggle="tooltip" data-bs-placement="top" title="Imprimir">
                    <button type="button" class="btn btn-success" onclick="window.open('{% url 'boletinoficial_pdf' boletinoficial.id %}', '_blank')"><i class="bi bi-printer"></i></button>
                  </span>
                  {% if not boletinoficial.publicado and boletinoficial.archivo_pdf %}
                  {% if perms.AppDigestoVillaNueva.admin_boletinoficial %}
                  <span data-bs-toggle="tooltip" data-bs-placement="top" title="Publicar">
                    <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#publicModal{{ boletinoficial.id }}"><i class="bi bi-book"></i></button>
                  </span>
                  {% endif %}
                  {% endif %}
                  {% if not boletinoficial.publicado %}
                  {% if perms.AppDigestoVillaNueva.delete_boletinoficial %}
                  <span data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar">
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ boletinoficial.id }}"><i class="bi bi-trash"></i></button>
                  </span>
                  {% endif %}
                  {% endif %}
                </td>
            </tr>
            <!-- Inicio Modal Eliminar -->
            <div class="modal fade" id="deleteModal{{ boletinoficial.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirmar eliminación</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <p class="text-center">¿Estás seguro de que deseas eliminar el <b>Boletin Oficial {{ boletinoficial.fecha_hasta|date:"d/m/Y" }}</b>?</p>
                    <p class="text-danger text-center"><b>¡Una vez eliminado no podrás recuperarlo!</b></p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <a href="{% url 'boletinoficial_delete' boletinoficial.id %}" class="btn btn-danger">Eliminar</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- Fin Modal Eliminar -->
            <!-- Inicio Modal Publicar -->
            <div class="modal fade" id="publicModal{{ boletinoficial.id }}" tabindex="-1" aria-labelledby="publicModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="publicModalLabel">Confirmar publicación</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <p class="text-center">¿Estás seguro de que deseas publicar el <b>Boletín Oficial {{ boletinoficial.fecha_hasta|date:"d/m/Y" }}</b>?</p>
                    <p class="text-danger text-center"><b>¡Una vez publicado no podrás deshacer la acción!</b></p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <a href="{% url 'boletinoficial_public' boletinoficial.id %}" class="btn btn-danger">Publicar</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- Fin Modal Publicar -->
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
  // Inicializar los tooltips
  var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl);
  });
</script>

<link rel="stylesheet" href="{% static 'style/jquery.dataTables.min.css' %}">
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script>
$(document).ready(function() {
    var table = $('#boletinoficialTable').DataTable({
        "order": [[ 0, "desc" ]],
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Spanish.json",
            "sLengthMenu": "_MENU_",
            "sInfo": "<h6 class='float-end'>Total de registros: _TOTAL_</h6>"
        },
        "initComplete": function() {
            // Aplicar clases de Bootstrap al campo de búsqueda
            $('div.dataTables_filter input').attr('placeholder', 'Buscar..');
            $('div.dataTables_filter label').contents().filter(function() {
                return this.nodeType === 3; // Node.TEXT_NODE
            }).remove();

            // Aplicar clases de Bootstrap al select de cantidad de registros a mostrar
            $('div.dataTables_length label').contents().filter(function() {
                return this.nodeType === 3; // Node.TEXT_NODE
            }).remove();
            $('div.dataTables_length label').prepend('Registros por página: ');

            // Aplicar clases de Bootstrap a la paginación
            $('div.dataTables_paginate').addClass('justify-content-center');
            $('div.dataTables_paginate a').addClass('btn btn-primary');
            $('div.dataTables_paginate a').css('margin', '0 2px');
        },
        "drawCallback": function() {
            // Aplicar clases de Bootstrap a la paginación en cada cambio de página
            $('div.dataTables_paginate a');
            $('div.dataTables_paginate a').css('margin', '0 2px');
        }
    });

    // Mover el campo de búsqueda y el select de cantidad de registros a la misma fila
    $('div.dataTables_filter').css('float', 'right');
    $('div.dataTables_length').css('float', 'left');
    $('div.dataTables_filter').appendTo('#boletinoficialTable_length');
});
</script>
{% endblock %}

AppDigestoVillaNueva/templates/boletinoficial/boletin_tapa.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <style>
        .header {
            text-align: center;
            margin: 50px;
        }
        .title {
            font-size: 3em;
        }
        .date {
            font-size: 2em;
            color: grey;
        }
        .logos {
            display: flex;
            justify-content: space-between;
            margin: 50px;
        }
        .logo {
            width: 20%;
            height: auto;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Boletín Oficial</div>
        <div class="date">{{ fecha_creacion }}</div>
    </div>
    <div class="logos">
        <img class="logo" src="{{ logo }}" alt="logo_mvn" style="width: 20%; height: auto;">
        <img class="logo" src="{{ logo }}" alt="logo_escudo" style="width: 20%; height: auto;">
    </div>    
</body>
</html>