AppDigestoVillaNueva/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from .views import *

urlpatterns = [
    path('', RedirectView.as_view(url='/home')),
    path('home/', login_required(index), name='index'),
    path('decreto-crear/', login_required(DecretoCreateView.as_view()), name='decreto_create'),
    path('decreto-editar/<int:pk>/', login_required(DecretoUpdateView.as_view()), name='decreto_update'),
    path('decreto-listar/', login_required(DecretoListView.as_view()), name='decreto_list'),
    path('decreto-publicar/<int:pk>/', login_required(DecretoPublicarView.as_view()), name='decreto_public'),
    path('decreto-publicar-masivo', login_required(DecretoPublicarMasivoView.as_view()), name='decreto_public_masivo'),
    path('decreto-eliminar/<int:pk>/', login_required(DecretoDeleteView.as_view()), name='decreto_delete'),
    path('decreto-pdf/<int:pk>/', login_required(decreto_pdf_view), name='decreto_pdf'),
    path('ordenanza-crear/', login_required(OrdenanzaCreateView.as_view()), name='ordenanza_create'),
    path('ordenanza-editar/<int:pk>/', login_required(OrdenanzaUpdateView.as_view()), name='ordenanza_update'),
    path('ordenanza-listar/', login_required(OrdenanzaListView.as_view()), name='ordenanza_list'),
    path('ordenanza-publicar/<int:pk>/', login_required(OrdenanzaPublicarView.as_view()), name='ordenanza_public'),
    path('ordenanza-publicar-masivo', login_required(OrdenanzaPublicarMasivoView.as_view()), name='ordenanza_public_masivo'),
    path('ordenanza-eliminar/<int:pk>/', login_required(OrdenanzaDeleteView.as_view()), name='ordenanza_delete'),
    path('ordenanza-pdf/<int:pk>/', login_required(ordenanza_pdf_view), name='ordenanza_pdf'),
    path('resolucion-crear/', login_required(ResolucionCreateView.as_view()), name='resolucion_create'),
    path('resolucion-editar/<int:pk>/', login_required(ResolucionUpdateView.as_view()), name='resolucion_update'),
    path('resolucion-listar/', login_required(ResolucionListView.as_view()), name='resolucion_list'),
    path('resolucion-publicar/<int:pk>/', login_required(ResolucionPublicarView.as_view()), name='resolucion_public'),
    path('resolucion-publicar-masivo', login_required(ResolucionPublicarMasivoView.as_view()), name='resolucion_public_masivo'),
    path('resolucion-eliminar/<int:pk>/', login_required(ResolucionDeleteView.as_view()), name='resolucion_delete'),
    path('resolucion-pdf/<int:pk>/', login_required(resolucion_pdf_view), name='resolucion_pdf'),
    path('declaracion-crear/', login_required(DeclaracionCreateView.as_view()), name='declaracion_create'),
    path('declaracion-editar/<int:pk>/', login_required(DeclaracionUpdateView.as_view()), name='declaracion_update'),
    path('declaracion-listar/', login_required(DeclaracionListView.as_view()), name='declaracion_list'),
    path('declaracion-publicar/<int:pk>/', login_required(DeclaracionPublicarView.as_view()), name='declaracion_public'),
    path('declaracion-publicar-masivo', login_required(DeclaracionPublicarMasivoView.as_view()), name='declaracion_public_masivo'),
    path('declaracion-eliminar/<int:pk>/', login_required(DeclaracionDeleteView.as_view()), name='declaracion_delete'),
    path('declaracion-pdf/<int:pk>/', login_required(declaracion_pdf_view), name='declaracion_pdf'),
    path('boletinoficial-crear', crear_boletin, name='boletinoficial_create'),
    path('boletinoficial/<int:pk>/', login_required(boletin_detail), name='boletinoficial_detail'),
    path('boletinoficial-listar/', login_required(BoletinOficialListView.as_view()), name='boletinoficial_list'),
    path('boletinoficial-pdf/<int:pk>/', login_required(boletin_pdf_view), name='boletinoficial_pdf'),
    path('boletinoficial-publicar/<int:pk>/', login_required(BoletinOficialPublicarView.as_view()), name='boletinoficial_public'),
    path('boletinoficial-eliminar/<int:pk>/', login_required(BoletinOficialDeleteView.as_view()), name='boletinoficial_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DigestoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppDigestoVillaNueva.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

AppDigestoVillaNueva/models.py
from django.db import models
from datetime import date
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from django.utils import timezone
import os


# Create your models here.

class Documento(models.Model):
    fecha_creacion = models.DateField(default=timezone.now)
    descripcion = models.TextField(max_length=2000)
    publicado = models.BooleanField(default=False)
    eliminado = models.BooleanField(default=False)
    creado_por = models.ForeignKey(User, on_delete=models.PROTECT, related_name='documentos_creados')
    ultima_modificacion = models.DateTimeField(auto_now=True)
    modificado_por = models.ForeignKey(User, on_delete=models.PROTECT, related_name='documentos_modificados')

def upload_to_decreto(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'Decretos/Decreto-{0}-{1:04d}{2}'.format(instance.anio, instance.numero_decreto, extension)

class Decreto(Documento):
    numero_decreto = models.PositiveIntegerField(default=1)
    anio = models.IntegerField(default=date.today().year)
    fecha_publicacion = models.DateField(blank=True, null=True)
    archivo_pdf = models.FileField(upload_to=upload_to_decreto, validators=[FileExtensionValidator(['pdf'], message="ERROR, el archivo tiene que estar en formato PDF.")], blank=True, null=True)

    def __str__(self):
        return "Decreto- " + str(self.anio) + "/" + str(self.numero_decreto)
    
    def save(self, *args, **kwargs):
        # Si el objeto ya existe y se está actualizando el archivo
        if self.pk and self.archivo_pdf:
            try:
                # Intenta obtener el objeto antiguo
                old_file = Decreto.objects.get(pk=self.pk).archivo_pdf
            except Decreto.DoesNotExist:
                pass
            else:
                # Si el archivo antiguo existe y es diferente del nuevo, bórralo
                if old_file and old_file != self.archivo_pdf:
                    old_file.delete()

        # Llama al método save de la clase base para continuar con el procesamiento estándar
        super().save(*args, **kwargs)
    
def upload_to_ordenanza(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'Ordenanzas/Ordenanza-{0}-{1:04d}{2}'.format(instance.anio, instance.numero_ordenanza, extension)

class Ordenanza(Documento):
    numero_ordenanza = models.PositiveIntegerField(default=1)
    anio = models.IntegerField(default=date.today().year)
    fecha_publicacion = models.DateField(blank=True, null=True)
    archivo_pdf = models.FileField(upload_to=upload_to_ordenanza, validators=[FileExtensionValidator(['pdf'], message="ERROR, el archivo tiene que estar en formato PDF.")], blank=True, null=True)

    def __str__(self):
        return "Ordenanza- " + str(self.anio) + "/" + str(self.numero_ordenanza)
    
    def save(self, *args, **kwargs):
        # Si el objeto ya existe y se está actualizando el archivo
        if self.pk and self.archivo_pdf:
            try:
                # Intenta obtener el objeto antiguo
                old_file = Ordenanza.objects.get(pk=self.pk).archivo_pdf
            except Ordenanza.DoesNotExist:
                pass
            else:
                # Si el archivo antiguo existe y es diferente del nuevo, bórralo
                if old_file and old_file != self.archivo_pdf:
                    old_file.delete()

        # Llama al método save de la clase base para continuar con el procesamiento estándar
        super().save(*args, **kwargs)

def upload_to_resolucion(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'Resoluciones/Resolucion-{0}-{1:04d}{2}'.format(instance.anio, instance.numero_resolucion, extension)

class Resolucion(Documento):
    numero_resolucion = models.PositiveIntegerField(default=1)
    anio = models.IntegerField(default=date.today().year)
    fecha_publicacion = models.DateField(blank=True, null=True)
    archivo_pdf = models.FileField(upload_to=upload_to_resolucion, validators=[FileExtensionValidator(['pdf'], message="ERROR, el archivo tiene que estar en formato PDF.")], blank=True, null=True)

    def __str__(self):
        return "Resolucion- " + str(self.anio) + "/" + str(self.numero_resolucion)
    
    def save(self, *args, **kwargs):
        # Si el objeto ya existe y se está actualizando el archivo
        if self.pk and self.archivo_pdf:
            try:
                # Intenta obtener el objeto antiguo
                old_file = Resolucion.objects.get(pk=self.pk).archivo_pdf
            except Resolucion.DoesNotExist:
                pass
            else:
                # Si el archivo antiguo existe y es diferente del nuevo, bórralo
                if old_file and old_file != self.archivo_pdf:
                    old_file.delete()

        # Llama al método save de la clase base para continuar con el procesamiento estándar
        super().save(*args, **kwargs)

def upload_to_declaracion(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'Declaraciones/Declaracion-{0}-{1:04d}{2}'.format(instance.anio, instance.numero_declaracion, extension)

class Declaracion(Documento):
    numero_declaracion = models.PositiveIntegerField(default=1)
    anio = models.IntegerField(default=date.today().year)
    fecha_publicacion = models.DateField(blank=True, null=True)
    archivo_pdf = models.FileField(upload_to=upload_to_declaracion, validators=[FileExtensionValidator(['pdf'], message="ERROR, el archivo tiene que estar en formato PDF.")], blank=True, null=True)

    def __str__(self):
        return "Declaracion- " + str(self.anio) + "/" + str(self.numero_declaracion)
    
    def save(self, *args, **kwargs):
        # Si el objeto ya existe y se está actualizando el archivo
        if self.pk and self.archivo_pdf:
            try:
                # Intenta obtener el objeto antiguo
                old_file = Declaracion.objects.get(pk=self.pk).archivo_pdf
            except Declaracion.DoesNotExist:
                pass
            else:
                # Si el archivo antiguo existe y es diferente del nuevo, bórralo
                if old_file and old_file != self.archivo_pdf:
                    old_file.delete()

        # Llama al método save de la clase base para continuar con el procesamiento estándar
        super().save(*args, **kwargs)

def upload_to_boletin(instance, filename):
    base, extension = os.path.splitext(filename)
    return 'BoletinOficial/BoletinOficial-{0}{1}'.format(instance.fecha_creacion, extension)

class BoletinOficial(models.Model):
    fecha_creacion = models.DateField(default=timezone.now)
    fecha_desde = models.DateField()
    fecha_hasta = models.DateField()
    publicado = models.BooleanField(default=False)
    decretos = models.BooleanField(default=False)
    resoluciones = models.BooleanField(default=False)
    ordenanzas = models.BooleanField(default=False)
    declaraciones = models.BooleanField(default=False)
    archivo_pdf = models.FileField(upload_to=upload_to_boletin, blank=True, null=True)

    def __str__(self):
        return "BoletinOficial-" + str(self.fecha_creacion)

AppDigestoVillaNueva/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, UpdateView, ListView, View
from django.urls import reverse_lazy
from datetime import date
from django.db.models import Max
from .models import Decreto
from .forms import DecretoForm
from datetime import datetime

# Create your views here.

class DecretoCreateView(CreateView):
    model = Decreto
    form_class = DecretoForm
    template_name = "decreto_create.html"
    success_url = reverse_lazy('decreto_list')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_initial(self):
        # Obtiene el valor máximo de numero_decreto del año actual + 1
        today = date.today()
        year = today.year
        max_decreto = Decreto.objects.filter(anio=year).aggregate(Max('numero_decreto'))['numero_decreto__max']

        # Si no hay ningún decreto para el año actual, asigna 1 como valor predeterminado
        if max_decreto is None:
            max_decreto = 1
        else:
            max_decreto += 1

        # Devuelve un diccionario con el valor predeterminado para numero_decreto
        return {'numero_decreto': max_decreto}
    
    def form_valid(self, form):
        # Obtén la fecha de publicación del formulario
        fecha_publicacion = form.cleaned_data.get('fecha_publicacion')

        # Si hay una fecha de publicación, establece publicado en True
        if fecha_publicacion:
            form.instance.publicado = True

        # Llama al método form_valid de la clase base para continuar con el procesamiento estándar
        return super().form_valid(form)

class DecretoUpdateView(UpdateView):
    model = Decreto
    form_class = DecretoForm
    template_name = "decreto_edit.html"
    success_url = reverse_lazy('decreto_list')

    def form_valid(self, form):
        # Obtén la fecha de publicación del formulario
        fecha_publicacion = form.cleaned_data.get('fecha_publicacion')

        # Si hay una fecha de publicación, establece publicado en True
        if fecha_publicacion:
            form.instance.publicado = True

        # Llama al método form_valid de la clase base para continuar con el procesamiento estándar
        return super().form_valid(form)

class DecretoListView(ListView):
    model = Decreto
    template_name = "decreto_list.html"
    context_object_name = 'decretos'
    
    def get_queryset(self):
        return Decreto.objects.filter(eliminado=False).order_by('-anio', '-numero_decreto')

class DecretoDeleteView(UpdateView):
    model = Decreto
    fields = ['eliminado']

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.eliminado = True
        self.object.save()
        return redirect('decreto_list')
    
class DecretoPublicarView(UpdateView):
    model = Decreto
    fields = ['publicado']

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.publicado = True
        self.object.fecha_publicacion = date.today()
        self.object.save()
        return redirect('decreto_list')

class DecretoPublicarMasivoView(View):
    def get(self, request):
        return render(request, 'decreto_publicacion_masiva.html')

    def post(self, request):
        if 'confirmar' in request.POST:
            # Si se confirma la publicación, publicar los decretos
            decretos_a_publicar_ids = request.session.get('decretos_a_publicar_ids', [])
            decretos_a_publicar = Decreto.objects.filter(id__in=decretos_a_publicar_ids)
            for decreto in decretos_a_publicar:
                decreto.publicado = True
                decreto.fecha_publicacion = date.today()
                decreto.save()
            del request.session['decretos_a_publicar_ids']  # Limpiar la sesión
            return redirect('decreto_list')
        else:
            # Obtener las fechas y filtrar los decretos
            fecha_desde = request.POST.get('fecha_desde')
            fecha_hasta = request.POST.get('fecha_hasta')
            if fecha_desde and fecha_hasta:
                fecha_desde = datetime.strptime(fecha_desde, '%Y-%m-%d').date()
                fecha_hasta = datetime.strptime(fecha_hasta, '%Y-%m-%d').date()
                decretos = Decreto.objects.filter(fecha_creacion__range=(fecha_desde, fecha_hasta))
                decretos_a_publicar = [decreto for decreto in decretos if decreto.archivo_pdf and not decreto.fecha_publicacion]
                # Almacenar los IDs de los decretos a publicar en la sesión
                request.session['decretos_a_publicar_ids'] = [decreto.id for decreto in decretos_a_publicar]
                return render(request, 'decreto_confirmar_publicacion.html', {'decretos': decretos_a_publicar})
            else:
                return redirect('decreto_list')


def decreto_pdf_view(request, pk):
    decreto = get_object_or_404(Decreto, pk=pk)
    
    with open(decreto.archivo_pdf.path, 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        filename = 'Decreto-{0}-{1:04d}.pdf'.format(decreto.anio, decreto.numero_decreto)
        response['Content-Disposition'] = 'inline; filename="{0}"'.format(filename)
        return response

AppDigestoVillaNueva/views/views_login.py
from django.shortcuts import  redirect, render
from django.views.generic import View

# Create your views here.

def index(request):
    return render(request, 'home.html')

AppDigestoVillaNueva/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Digesto Villa Nueva</title>
  <link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'style/bootstrap-icons.css' %}">
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg" style="background-color: #9EC8B9;">
    <div class="container-fluid">
      <a class="navbar-brand">Digesto Villa Nueva</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Inicio</a>
          </li>
          {% if perms.AppDigestoVillaNueva.view_decreto or perms.AppDigestoVillaNueva.add_decreto %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Decretos
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'decreto_list' %}">Listado</a></li>
              <hr>
              {% if perms.AppDigestoVillaNueva.add_decreto %}
              <li><a class="dropdown-item" href="{% url 'decreto_create' %}">Nuevo</a></li>
              {% endif %}
              {% if perms.AppDigestoVillaNueva.admin_decreto %}
              <li><a class="dropdown-item" href="{% url 'decreto_public_masivo' %}">Publicación masiva</a></li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
          {% if perms.AppDigestoVillaNueva.view_ordenanza or perms.AppDigestoVillaNueva.add_ordenanza %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Ordenanzas
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'ordenanza_list' %}">Listado</a></li>
              <hr>
              {% if perms.AppDigestoVillaNueva.add_ordenanza %}
              <li><a class="dropdown-item" href="{% url 'ordenanza_create' %}">Nueva</a></li>
              {% endif %}
              {% if perms.AppDigestoVillaNueva.admin_ordenanza %}
              <li><a class="dropdown-item" href="{% url 'ordenanza_public_masivo' %}">Publicación masiva</a></li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
          {% if perms.AppDigestoVillaNueva.view_resolucion or perms.AppDigestoVillaNueva.add_resolucion %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Resoluciones
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'resolucion_list' %}">Listado</a></li>
              <hr>
              {% if perms.AppDigestoVillaNueva.add_resolucion %}
              <li><a class="dropdown-item" href="{% url 'resolucion_create' %}">Nueva</a></li>
              {% endif %}
              {% if perms.AppDigestoVillaNueva.admin_resolucion %}
              <li><a class="dropdown-item" href="{% url 'resolucion_public_masivo' %}">Publicación masiva</a></li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
          {% if perms.AppDigestoVillaNueva.view_declaracion or perms.AppDigestoVillaNueva.add_declaracion %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Declaraciones
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'declaracion_list' %}">Listado</a></li>
              <hr>
              {% if perms.AppDigestoVillaNueva.add_declaracion %}
              <li><a class="dropdown-item" href="{% url 'declaracion_create' %}">Nueva</a></li>
              {% endif %}
              {% if perms.AppDigestoVillaNueva.admin_declaracion %}
              <li><a class="dropdown-item" href="{% url 'declaracion_public_masivo' %}">Publicación masiva</a></li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
          {% if perms.AppDigestoVillaNueva.view_boletinoficial or perms.AppDigestoVillaNueva.add_boletinoficial %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Boletín Oficial
            </a>
            <ul class="dropdown-menu">
              {% if perms.AppDigestoVillaNueva.view_declaracion %}
              <li><a class="dropdown-item" href="{% url 'boletinoficial_list' %}">Listado</a></li>
              {% endif %}
              <hr>
              {% if perms.AppDigestoVillaNueva.add_declaracion %}
              <li><a class="dropdown-item" href="{% url 'boletinoficial_create' %}">Nuevo</a></li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
        </ul>
      </div>
      <form class="d-flex">
        <a class="btn btn-light" href="{% url 'logout' %}">Cerrar Sesión</a>
      </form>
    </div>
  </nav>

  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
</body>

</html>

AppDigestoVillaNueva/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<br><br>
<div class="text-center">
  <img src="{% static 'images/logo_mvn.png' %}" alt="logo_mvn" style="width: 20%; height: auto;">
</div>
<br>
<h4 class="text-center">¡Bienvenido al Digesto Municipal de Villa Nueva!</h4>
<br>
<div class="row row-cols-1 row-cols-md-4 g-4">
    {% if perms.AppDigestoVillaNueva.view_decreto or perms.AppDigestoVillaNueva.add_decreto %}
    <a href="{% url 'decreto_list' %}">
    <div class="col">
      <div class="card">
        <img src="{% static 'images/home-1.png' %}" class="card-img-top" alt="Decretos">
        <div class="card-body">
          <h5 class="card-title text-center">Decretos</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    </a>
    {% endif %}
    {% if perms.AppDigestoVillaNueva.view_resolucion or perms.AppDigestoVillaNueva.add_resolucion %}
    <a href="{% url 'resolucion_list' %}">
    <div class="col">
      <div class="card">
        <img src="{% static 'images/home-2.png' %}" class="card-img-top" alt="Resoluciones">
        <div class="card-body">
          <h5 class="card-title text-center">Resoluciones</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    </a>
    {% endif %}
    {% if perms.AppDigestoVillaNueva.view_ordenanza or perms.AppDigestoVillaNueva.add_ordenanza %}
    <a href="{% url 'ordenanza_list' %}">
    <div class="col">
      <div class="card">
        <img src="{% static 'images/home-3.png' %}" class="card-img-top" alt="Ordenanzas">
        <div class="card-body">
          <h5 class="card-title text-center">Ordenanzas</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    </a>
    {% endif %}
    {% if perms.AppDigestoVillaNueva.view_declaracion or perms.AppDigestoVillaNueva.add_declaracion %}
    <a href="{% url 'declaracion_list' %}">
    <div class="col">
      <div class="card">
        <img src="{% static 'images/home-4.png' %}" class="card-img-top" alt="Declaraciones">
        <div class="card-body">
          <h5 class="card-title text-center">Declaraciones</h5>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
    </a>
    {% endif %}
  </div>

{% endblock %}